# Meta
title: Eluseum Aqueropa
author: pojntfx
email: felix@pojtinger.com
description: >-
  A website with everything you could possibly want to know about aquatics.

# Config
baseurl: ""
url: "https://aqeuropa.tk/"
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Plugins
plugins:
  - jekyll-admin
jekyll_admin:
  hidden_links:
    - datafiles # We do not have any data files currently